baseURL = "LucaBartolini/LucaBartolini.github.io"
# baseURL = "localhost"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hello-friend-ng"
# publishDir  = "public"
publishDir  = "docs"
paginate     = 10
